EmbarkStudios/spirt

src/spv/lower.rs
Looks like an accidental omission originally - found while trying to align `rustc_codegen_spirv::linker::test` unit tests so SPIR-T doesn't affect them (for https://github.com/EmbarkStudios/rust-gpu/pull/940#issuecomment-1323128422).
=> spv/lower: set `FuncParam` attrs to those attached to `OpFunctionParameter`.

src/spv/lift.rs
As we have no `break` edges out of SPIR-T loop bodies, any point in the loop body (not nested in another selection/loop) is a valid "continue" target, and we can spare a block by making *the whole body* that.
In [WGSL loops](https://gpuweb.github.io/gpuweb/wgsl/#loop-statement), this corresponds to moving the rest of the loop body (*not* using `break`/`continue`) into the `continuing {...}` block. <sub>(but examples are hard because `break if` isn't implemented yet in Naga, and our `do`-`while`-style loops use SPIR-V "conditional back-edges" which in WGSL *require* `break if` - see https://github.com/gfx-rs/naga/issues/1977#issuecomment-1318334723 for more details/context)</sub>
For `tests/data/for-loop.wgsl.spvasm` (after `spirv-as` -> `spv-lower-link-lift` -> `spirv-dis`), the change …
=> spv/lift: use loop body entry (instead of exit), as the "continue" target.

examples/spv-lower-lift-roundtrip.rs, examples/spv-read-write-roundtrip.rs, src/print/mod.rs, src/spv/lower.rs, src/spv/print.rs, src/spv/read.rs, src/spv/spec.rs, src/spv/write.rs
This is new on nightly - result looks great, but it being flipped on broke our CI.
=> Unbreak CI via `cargo clippy --fix` (for `clippy::uninlined-format-args`).

src/cfg.rs, src/context.rs, src/func_at.rs, src/lib.rs, src/passes/link.rs, src/print/mod.rs, src/print/pretty.rs, src/spv/lift.rs, src/spv/lower.rs, src/spv/print.rs, src/spv/read.rs, src/spv/spec.rs, src/spv/write.rs
In no particular order, these are the suspicious and/or not-entirely-addressed lints:
* `clippy::single_match_else`: permanently `#![allow(…)]`ed, as the style it denies is important for readability
* `clippy::string_add`: permanently `#![allow(…)]`ed, as it's (IMO) misguided (and perhaps buggy?)
* `(...: String) + "..."` is short for `{ let mut s = ...; s.push_str("..."); s }`, *not something else*
* `clippy::match_same_arms`: `#[allow(…)]` moved to specific `match`es where listing out the patterns individually is more important than what the actual values are (i.e. grouping by the output values is detrimental)
* `clippy::should_implement_trait`: `#![allow(…)]` moved to specific module encountering this bug:
* https://github.com/rust-lang/rust-clippy/issues/5004
* `clippy::unused_self`: …
=> Triage the list of allowed lints, addressing most of them.

.github/workflows/rustdoc-pages.yml, CHANGELOG.md, Cargo.toml, README.md, src/cfg.rs, src/context.rs, src/func_at.rs, src/lib.rs, src/passes/legalize.rs, src/passes/link.rs, src/print/mod.rs, src/print/pretty.rs, src/spv/lift.rs, src/spv/lower.rs, src/spv/mod.rs, src/spv/print.rs, src/spv/spec.rs, src/transform.rs, src/visit.rs
Closes #8 - the additions are pretty sparse, but the result should be far easier to navigate.
=> Start filling in minimal crate docs.

CHANGELOG.md, src/print/mod.rs, src/print/pretty.rs, src/spv/print.rs
The main observation here is that *since* picking most of the SPIR-T pretty-printing styles, I've started using RA inlays set to a tiny size, e.g.:
It's probably a more subjective choice, but on a 4K monitor the result is quite crisp.
In contrast to this, SPIR-T styles used a lot of "low visibility" but never shrinking text, which now feels worse.
---
On the other hand, I've been working on some experiments (involving pointers), and some instructions and attributes unique/specific to SPIR-T, and when those are not visually distinguishable from SPIR-V, it can get confusing.
This PR tries to tackle a bit of all that, the result is:
|[**Before**](https://htmlpreview.github.io/?https://gist.github.com/eddyb/405e25ff9689176cdcc15ace4b7c5c3b/raw/0-before-spirt%252321-mouse-shader.post-merge.link …
=> pretty: prefer shrinking instead of thinning text, and make SPIR-V ops/enums more distinct.

CHANGELOG.md
I updated the SPIRV-headers to latest.
Since I'm adding mesh shader support to rust-gpu, this is required to make it work!
=> Update SPIRV-headers to latest

CHANGELOG.md, Cargo.toml, src/cfg.rs, src/print/mod.rs, src/print/multiversion.rs, src/print/pretty.rs
This extra step, just before turning multi-version pretty-printed fragments into a HTML table row, allows for a clearer visual match between the columns, turning the multi-version mode into something closer to a pass "differ", but the use of *anchors* (instead of line contents) makes it more conservative, reliable and somewhat simpler.
In short, if two adjacent versions contain a *definition* like `v123 = ...`, it should now end up on the same horizontal line in both versions (assuming it's not e.g. out of order wrt most of the other definitions).
Before, adding or removing instructions (or even their pretty-printing needing different line amounts) would result in one side being behind (and the other, ahead), which would accumulate (even if most of their contents might be similar or even …
=> print: align adjacent multi-version columns' lines, to match up their anchors.

CHANGELOG.md, src/lib.rs, src/print/mod.rs, src/spv/lift.rs, src/visit.rs
This is an easy way to annotate the IR (anything that supports attributes) with diagnostics that would otherwise have a hard time being reported in a way that correlates with the definition they relate to (without a full-on diagnostic system).
Example from an WIP version of #24:
=> Allow embedding diagnostics into SPIR-T as attributes.

CHANGELOG.md, examples/spv-lower-link-qptr-lift.rs, src/context.rs, src/func_at.rs, src/lib.rs, src/passes/legalize.rs, src/passes/qptr.rs, src/print/mod.rs, src/qptr/analyze.rs, src/qptr/layout.rs, src/qptr/lift.rs, src/qptr/lower.rs, src/qptr/mod.rs, src/qptr/shapes.rs, src/spv/lift.rs, src/spv/lower.rs, src/spv/mod.rs, src/spv/print.rs, src/spv/read.rs, src/spv/spec.rs, src/spv/write.rs, src/transform.rs, src/visit.rs
* name stands for "`q`uasi-`p`oin`t`e`r`" <sub><sup>(alternatively, "`q`uantum")</sup></sub>, in the sense of "not quite (a pointer)"
* <sub>(primarily chosen to distinguish it from both SPIR-V pointers and LLVM-style untyped `ptr`s)</sub>
* **untyped** _as a design principle_ ("behavior given by operations, not types")
* maximally so, not even tracking the address space ("Storage Class"), unlike e.g. LLVM `ptr`s
* comparable to OpenCL `Generic` physical pointers (but more flexible and without runtime behavior)
* **for Rust-GPU**, this allows faithfully representing Rust's *untyped memory* semantics
* <sub>(Rust also lacks explicit address spaces, and `qptr` can replace Rust-GPU's "Storage Class" inference pass)</sub>
* **for legalization/optimization**, existing approaches (from IRs with …
=> Introduce `qptr` ("quasi-pointer") type and associated lower->analyze->lift passes.

src/print/mod.rs
* the first commit is the same fix as https://github.com/EmbarkStudios/rust-gpu/pull/1043
* the second commit fixes a layout issue (where multi-line `/* ... */` didn't indent at the right level)
Combined we have this example:
<sub>(the specific message is still a bit whacky but it's only a BUG)</sub>
|Before this PR|After this PR|
|-|-|
|![image](https://user-images.githubusercontent.com/77424/235386845-418f790c-52ec-455b-9630-c621729bc7ba.png)|![image](https://user-images.githubusercontent.com/77424/235386717-081ef62a-4baa-4420-944e-be9454ecae18.png)|
=> print: fix a couple bugs in the initial diagnostics PR.

CHANGELOG.md, src/context.rs, src/func_at.rs, src/lib.rs, src/passes/legalize.rs, src/passes/link.rs, src/passes/qptr.rs, src/print/mod.rs, src/qptr/analyze.rs, src/qptr/lift.rs, src/qptr/lower.rs, src/qptr/mod.rs, src/qptr/shapes.rs, src/spv/lift.rs, src/spv/lower.rs, src/spv/mod.rs, src/transform.rs, src/visit.rs
This should, in theory, allow reusing one `DataInst` "form" (or "template") for many `DataInst`s, with only runtime inputs (and/or attributes) differing between their "instances".
While there is no good reason to have the extra indirection today (and the performance impact seems to fall within noise), there is a refactor I want to try (which would require multiple outputs per `DataInst`, and that would add to the growing size of `DataInstDef`, before this interning change).
~~Will keep this PR as draft until I can confirm that refactor is successful.~~
=> Intern, as `DataInstForm`, the `kind` and `output_type` fields of `DataInstDef`.

CHANGELOG.md, src/print/mod.rs, src/print/multiversion.rs, src/print/pretty.rs
*Originally found/fixed during the #33/#34/#35/#36 series of pretty-printing PRs.*
Before this PR, we were treating all text the same, regardless of style, but this PR introduces the concept of "fractional columns" (integer multiples of `0.1ch`, because our `font-size`s are always integer multiples of `0.1em`).
The result is much more accurate, and so far appears to perfectly match browser behavior (i.e. the transition of `MAX_LINE_WIDTH` from `N-1` to `N`, where multi-line layout gets replaced with single-line layout, results in a line that "tightly fits" in a `max-width: Nch` container, with no spurious gaps or overflows).
Note however that the increased accuracy makes the layout favor HTML over plaintext (and we don't have a plaintext-vs-HTML "simultaneous layout", nor a way to hint …
=> print: accurately track (fractional) line width, and raise the max width back to 120.

CHANGELOG.md, README.md, src/print/mod.rs, src/spv/print.rs, src/spv/spec.rs
There's two main changes here:
- removal of *all* angle brackets (`<...>`) from SPIR-T pretty-printing
- they used to be used for *immediates* (almost as if they were "const generics", to distinguish them from regular inputs/arguments, which used parens)
- may have had some use in quickly visualizing what the "immediates"/"inputs" split may be, but I don't recall actually relying on that, and it's probably better to have SPIR-T-"native" forms for any aspects of SPIR-V we care about
- new style uses the standard SPIR-V order (interleaving immediates and ID operands)
- long term this *may* make it easier to parse a SPIR-T textual form (but there are no current plans for that)
- introduction of "named argument" labels (`foo:` before an operand)
- for SPIR-V ops and enumerands, this should …
=> print: use `spv.OpFoo(A: imm, B: ID, C: imm, ...)` instead of `spv.OpFoo<imms>(IDs)`.

CHANGELOG.md, README.md, src/print/mod.rs
This moves us from my ad-hoc `#{A, B, C}` to a Rust-style `#[A] #[B] #[C]` attribute syntax, and removes the idea of a "attribute set shorthand" (`attrs123 = #{...}` followed by uses of `#attrs123`), which was more annoying than useful (attributes can't refer to other attributes so there was no "exponential deduplication" need for it).
With `#[...]` syntax, it also makes sense to never say e.g. `OpDecorate` (as the operand itself will contain the word `Decoration`), or to use `#[name = "..."]` Rust-style syntax for `OpName`.
(I didn't touch `OpMember{Name,Decorate}`, might be worth having a SPIR-T `struct` type declaration syntax just to clean those up but it feels even more ad-hoc than usual - maybe it might make more sense after #36?)
Comparison (using Kajiya's …
=> print: always print attributes inline and with per-attribute `#[...]` syntax.

CHANGELOG.md, Cargo.toml, deny.toml, src/lib.rs, src/print/mod.rs, src/qptr/mod.rs, src/spv/lower.rs, src/visit.rs
`print::Node` used to contain both `Root` (which is user-specified and could be any `Visit+Print` type), and specific node types (such as interned `Type`s/`Const`s, and `Module`-owned `GlobalVar`s/`Func`s), which never needed dynamic dispatch but were forced to use it anyway, because `Node::Root`s needed it.
The other conflation was caused by the fact that non-root node types need to implement `Print<Output = AttrsAndDef>`, because they have *names* that have to be inserted (in between attributes and the rest of the definition), but the root has no such requirement, since it's self-contained and only its dependencies need to be named.
By treating roots separately, we can require `Print<Output = pretty::Fragment>` instead for roots, which fixes a long-term annoyance where pretty-printing …
=> print: separate "roots" from "nodes" and only use dynamic dispatch for roots.

CHANGELOG.md, README.md, src/print/mod.rs
This is something I realized while looking at the output of #36, where keywords like `type` or `const` were overly verbose.
I've kept the keywords but only on definitions, so e.g. `type T5 = ...` is referred to as `T5`.
Comparison (using Kajiya's `assets/shaders/ircache/raster_origins_vs.hlsl`, compiled by DXC):
|[**Before**](https://htmlpreview.github.io/?https://gist.github.com/eddyb/809b734460afeaa5c72c31992c9d0bbb/raw/0-before-spirt%252339-raster_origins_vs.hlsl.structured.spirt.html)<br><sub>(click for complete pretty HTML example)</sub>|[**After**](https://htmlpreview.github.io/?https://gist.github.com/eddyb/809b734460afeaa5c72c31992c9d0bbb/raw/1-after-spirt%252339-raster_origins_vs.hlsl.structured.spirt.html)<br><sub>(click for complete pretty HTML example)</sub>|
|-|-| …
=> print: shorten names like `type2`/`func3`/etc. to `T2`/`F3`/etc.

CHANGELOG.md, src/print/mod.rs, src/print/multiversion.rs, src/print/pretty.rs, src/spv/mod.rs
I've also made the `T1` style use subscripts (so more like `T₁`), because I wasn't happy with the aesthetics of having digits exactly as large as the prefix.
The reason I haven't done the subscript change earlier is e.g. `v5` already looks great, and `v₅` and `T₅` still looks different because the `T` is larger than the `v` - the missing trick was to make the subscripts larger when the prefix is uppercase, which seems to balance things out.
Comparison (using Kajiya's `assets/shaders/ircache/raster_origins_vs.hlsl`, compiled by DXC, like #39):
|[**Before**](https://htmlpreview.github.io/?https://gist.github.com/eddyb/22a1468ce5341e822e95204a91406897/raw/0-before-spirt%252336-raster_origins_vs.hlsl.structured.spirt.html)<br><sub>(click for complete pretty HTML …
=> print: use `OpName`s to replace the `T1`/`F2`/`v3` style, when unambiguous.

examples/spv-lower-link-lift.rs, examples/spv-lower-link-qptr-lift.rs, examples/spv-lower-print.rs, rustfmt.toml, src/cfg.rs, src/context.rs, src/func_at.rs, src/lib.rs, src/passes/link.rs, src/print/mod.rs, src/print/multiversion.rs, src/print/pretty.rs, src/qptr/analyze.rs, src/qptr/layout.rs, src/qptr/lift.rs, src/qptr/lower.rs, src/qptr/mod.rs, src/spv/lift.rs, src/spv/lower.rs, src/spv/mod.rs, src/spv/print.rs, src/spv/read.rs, src/spv/spec.rs, src/spv/write.rs, src/transform.rs, src/visit.rs
This removes just over 1000 lines that only existed because `rustfmt`'s default decided to use multiple lines for e.g. method call chains that could just as well fit on one line.
Will require some gymnastics to handle rebasing on top but this feels big enough that I'm pushing it through.
=> Set `use_small_heuristics = "Max"` in `rustfmt.toml` to disable iffy heuristics.

CHANGELOG.md, build.rs, src/context.rs, src/print/mod.rs, src/spv/spec.rs
Rust-GPU benefits the most from this, with its new custom `OpExtInst`s for debuginfo:
|Before|After|
|-|-|
|<img src="https://github.com/EmbarkStudios/spirt/assets/77424/83a8c9cf-6c31-4b92-a0fe-e668a8a21d0b" height="500">|![image](https://github.com/EmbarkStudios/spirt/assets/77424/b8dec870-3e5d-4936-bdbc-b932a656d2fe)|
It also works great for seeing how Rust-GPU's new custom `Abort` converts to a `debugPrintf`:
|Before|![image](https://github.com/EmbarkStudios/spirt/assets/77424/a829b4a1-32cc-413f-90fd-aebf8148ece0)|
|-|-|
|**After**|![image](https://github.com/EmbarkStudios/spirt/assets/77424/ace358bd-e244-4229-8929-579e040f7c75)|
=> Pretty-print `OpExtInst` using official `extinst.*.grammar.json` and/or custom `Context`-registered ones.

CHANGELOG.md, README.md, build.rs, src/cfg.rs, src/print/mod.rs, src/spv/lower.rs
Quoting from the comment I added to the code:
> This analysis was added to because of two observations wrt "reconvergence":
> 1. syntactic loops (from some high-level language), when truly structured
>    (i.e. only using `while`/`do`-`while` exit conditions, not `break` etc.),
>    *always* map to "minimal loops" on a CFG, as the only loop exit edge is
>    built-in, and no part of the syntactic "loop body" can be its successor
> 2. more pragmatically, compiling shader languages to SPIR-V seems to (almost?)
>    always *either* fully preserve syntactic loops (via SPIR-V `OpLoopMerge`),
>    *or* structurize CFGs in a way that produces "minimal loops", which can
>    be misleading with explicit `break`s (moving user code from just before
>    the `break` to after the loop), but is less …
=> cfg: use Tarjan's SCC algorithm to get "minimal loops" (instead of "maximal").

CHANGELOG.md, src/cfg.rs, src/lib.rs, src/passes/qptr.rs, src/print/mod.rs, src/qptr/analyze.rs, src/qptr/layout.rs, src/qptr/lift.rs, src/qptr/lower.rs, src/qptr/mod.rs, src/spv/lift.rs, src/spv/lower.rs, src/spv/read.rs, src/transform.rs, src/visit.rs
The "constructor" idea was cute, but a mistake. At the end of the day (see #1, #50, #29), the direction to move into is simpler and/or flatter types and constants, *not* favoring the hierarchical ones.
=> Combine `TypeCtor`/`ConstCtor` and "ctor args" into a single `TypeKind`/`ConstKind`.

.github/workflows/ci.yml
https://github.com/EmbarkStudios/spirt/pull/57#pullrequestreview-1805470744
It means we don't really have repeatable CI checks, but the practical benefits probably outweighs that (and if someone would like to pick up an old branch to work with an old rust-gpu version for whatever strange reason, this check can easily be modified or removed).
=> Ensure compatibility with rust-gpu nightly rust in CI

CHANGELOG.md, README.md, src/cfg.rs, src/lib.rs, src/spv/lower.rs
Original motivation back when I first started this refactor was this bug:
- https://github.com/EmbarkStudios/rust-gpu/issues/1086
Progress stalled back then and I only revived the branch for the Vulkan layer (https://github.com/EmbarkStudios/spirt/pull/53), because trying to run the Vulkan CTS with the SPIR-T layer would run into:
- missing `OpSpecConstantOp` support (already implemented in the Vulkan layer branch)
- structurizer region desync `list_eq_key` panics (fixed by this PR)
- missing `OpTypeForwardPointer` support (not implemented yet, but it's much rarer and only used with `PhysicalStorageBuffer` pointers, since logical pointers don't allow recursive data types in the first place)
On top of unblocking the SPIR-T Vulkan layer for in-depth testing, this refactor, out of necessity …
=> cfg: reuse original `ControlRegion`s as much as possible during structurization.
